on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

name: Run tests

jobs:

  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run checks with Tox
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: poetry krb5-devel

    strategy:
      matrix:
        tox_env:
          - lint
          - format
  
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests with Tox
        uses: fedora-python/tox-github-action@main
        with:
          tox_env: ${{ matrix.tox_env }}
          dnf_install: limnoria poetry krb5-devel

    strategy:
      matrix:
        tox_env:
          - py36
